Update format_check.yaml

diff --git a/.github/workflows/format_check.yaml b/.github/workflows/format_check.yaml
--- a/.github/workflows/format_check.yaml
+++ b/.github/workflows/format_check.yaml
@@ -21,8 +21,9 @@ jobs:
       - name: Check code formatting with Clang Format
         id: clang-format-check
         run: |
-          find src -iname *.h -o -iname *.cpp | xargs clang-format -style=file -output-replacements-xml
-        continue-on-error: true
-
-      - name: Check formatting status
-        run: exit ${{ steps.clang-format-check.outcome }}
+          if clang-format -style=file -output-replacements-xml src/*.cpp src/*.h; then
+            echo "Code formatting check passed."
+          else
+            echo "Code formatting check failed."
+            exit 1
+          fi
